diff --git a/Makefile b/Makefile
index 8e3073b..93962ad 100644
--- a/Makefile
+++ b/Makefile
@@ -1,10 +1,12 @@
 # Makefile for TLP
 
+LIBDIR ?= lib
+
 SBIN  = $(DESTDIR)/usr/sbin
 BIN   = $(DESTDIR)/usr/bin
 PMETC = $(DESTDIR)/etc/pm/power.d
-TLIB  = $(DESTDIR)/usr/lib/tlp-pm
-PLIB  = $(DESTDIR)/usr/lib/pm-utils
+TLIB  = $(DESTDIR)/usr/$(LIBDIR)/tlp-pm
+PLIB  = $(DESTDIR)/usr/$(LIBDIR)/pm-utils
 ULIB  = $(DESTDIR)/lib/udev
 ACPI  = $(DESTDIR)/etc/acpi
 NMDSP = $(DESTDIR)/etc/NetworkManager/dispatcher.d
@@ -24,25 +26,25 @@ install-tlp:
 	# Package tlp
 	install -D -m 755 tlp $(SBIN)/tlp
 	install -D -m 755 tlp-rf $(BIN)/bluetooth
-	ln -f $(BIN)/bluetooth $(BIN)/wifi
-	ln -f $(BIN)/bluetooth $(BIN)/wwan
+	ln -fs $(BIN)/bluetooth $(BIN)/wifi
+	ln -fs $(BIN)/bluetooth $(BIN)/wwan
 	install -m 755 tlp-run-on $(BIN)/run-on-ac
-	ln -f $(BIN)/run-on-ac $(BIN)/run-on-bat
+	ln -fs $(BIN)/run-on-ac $(BIN)/run-on-bat
 	install -m 755 tlp-stat $(BIN)/
 	install -m 755 tlp-usblist $(BIN)/
 	install -m 755 tlp-pcilist $(BIN)/
+ifeq ($(origin TLP_NO_TPACPI), undefined)
 	install -D -m 755 tpacpi-bat $(TLIB)/tpacpi-bat
-	install -m 755 tlp-functions $(TLIB)/
+endif
+	install -D -m 755 tlp-functions $(TLIB)/tlp-functions
 	install -m 755 tlp-rf-func $(TLIB)/
 	install -m 755 tlp-nop $(TLIB)/
 	install -D -m 755 tlp-usb-udev $(ULIB)/tlp-usb-udev
 	install -D -m 644 tlp.rules $(ULIB)/rules.d/40-tlp.rules
 	[ -f $(CONFFILE) ] || install -D -m 644 default $(CONFFILE)
-	install -D -m 755 tlp.init $(DESTDIR)/etc/init.d/tlp
 	install -D -m 755 49tlp $(PLIB)/sleep.d/49tlp
 	install -D -m 644 thinkpad-radiosw $(ACPI)/events/thinkpad-radiosw
 	install -m 755 thinkpad-radiosw.sh $(ACPI)/
-	install -D -m 644 tlp.bash_completion $(DESTDIR)/etc/bash_completion.d/tlp
 
 install-rdw:
 	# Package tlp-rdw
